apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    gcpsm:
      projectID: robertb724-personal
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            key: key.json
            namespace: external-secrets
